version: '3.9'
services:  
  db:
    image: mysql:5.7
    restart: always
    ports: 
      - "3309:3306"
    environment:
      MYSQL_DATABASE: 'project'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    ports:
      - 8082:80
    volumes:
      - ./:/var/www/html    